sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CC=gcc-5 CXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: CC=clang-3.8 CXX=clang++-3.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y dh-autoreconf libtool doxygen graphviz
script:
  - ./bootstrap
  - ./configure CC=$CC CXX=$CXX
  - make
  - make check

